### ISSUE TITLE
cjk width problem

### ISSUE THREAD

**Issue by disjukr** [bcoe/cliui#14]
sorry i'm not good at english

![-2015-11-14- -6 41 00](https://cloud.githubusercontent.com/assets/690661/11162980/4aa85676-8b00-11e5-8aa1-c14daff0e605.png)

**Comment by bcoe** [comment]
@disjukr do you think you could add a failing unit test? I will happily sit down and try to figure out the wrapping issue once I have one :)

**Comment by disjukr** [comment]
i'll try now :D

**Comment by disjukr** [comment]
oh sorry; i think it's not cliui's problem.. cliui's cjk wrapping seems working well
maybe the problem was here: https://github.com/bcoe/yargs/blob/master/lib%2Fusage.js#L263

**Comment by bcoe** [comment]
@disjukr great find, that line should take into account utf-8 escape sequences., still up for adding a test to yargs? We can pull in @sindresorhus' string-width module:

https://github.com/sindresorhus/string-width

**Comment by bcoe** [comment]
\o/ solved in yargs.
