### ISSUE TITLE
Switch to wrap-ansi module

### ISSUE THREAD

**Issue by phated** [bcoe/cliui#6]
We are using `yargs` in gulp-cli and use chalk to color the descriptions.  I noticed that things start to get messed up due to the wordwrap module that is utilized.  I switched it out in my local install for [wrap-ansi](https://github.com/chalk/wrap-ansi) (by the chalk team) and it fixed the problem.

**Comment by bcoe** [comment]
Cool, happy to make the switch.

**Comment by phated** [comment]
It seems the tests are now failing, so there must be some differences between the 2 libraries.  I don't have enough experience with wordwrap, wrap-ansi or this module to dive in.  Going to cc @sindresorhus here.

**Comment by bcoe** [comment]
@sindresorhus @phated had the time to sit down and look at this request, the problem I'm running into is that we'd need for wrap-ansi to have support for hard wrapping:

https://github.com/substack/node-wordwrap#wraphardstart-stop

complex multi-column layout starts to look crazy if wrapping isn't enforced at a boundary.

**Comment by sindresorhus** [comment]
I've opened an issue about adding a hardwrap option: https://github.com/chalk/wrap-ansi/issues/2

I probably won't have time to look into this right now, though. Maybe @Qix- @dthree does.

**Comment by dthree** [comment]
@bcoe afik`wrap-ansi` wasn't designed to let words go beyond the boundary, i.e. I believe a semblance of "hard wrapping" is the default. It probably doesn't pad the columns where the word is shorter than the boundary, so that might be the problem.

Can you post a test string with multiple columns that reproduces the unexpected behavior?

**Comment by bcoe** [comment]
see: https://github.com/chalk/wrap-ansi/pull/3

**Comment by phated** [comment]
@bcoe thanks for digging into this.  Much appreciated.

**Comment by nexdrew** [comment]
Warning: shameless self-plug!

@phated If you're also interested in styling the output defined by `yargs` itself (e.g. `Options:`), take a look at [`yargonaut`](https://github.com/nexdrew/yargonaut) - allows you to easily decorate `yargs` strings with chalk styles and/or figlet fonts. Some related discussion in [`yargs` issue 251](https://github.com/bcoe/yargs/issues/251) as well.

:smiley_cat:

**Comment by bcoe** [comment]
@phated @nexdrew I've got a [pull ready to go on yargs](https://github.com/bcoe/yargs/pull/277) that adds ansi color support to the UI using wrap-ansi. Could you give this branch a shot with wrap-ansi and yargonaut, and see if it does the trick for you?

**Comment by bcoe** [comment]
@phated @nexdrew I've published `+ yargs@3.28.0` on the `next` tag with support for ansi escape codes, give it a shot and if things seem stable on our testing projects I'll promote it to `latest`:

`npm install yargs@next`

Have a great weekend.
